#!/usr/bin/env python3
'''
Small, simplistic model of the local heating 
generated by datacenters on boundary layer
'''
import numpy as np

sigma = 5.67e-8

def radiative_wind_model():
    alpha=0.3
    emiss=0.85
    #future implementation of a function to model the solar flux through day and night
    #See if time equilibrium << day
    S_flux= 1370./4. #W.m^-2
    Q_dc = 1000 #W.m^-2
    U_wind = 0.01   #m.s^-1
    rho = 1.293 #kg.m^-3
    cp = 1004 #J.(kg.K)^-1
    Cw = 1
    T_env = 23 + 273.15 #K

    A = (1-emiss/2.)*sigma

    B =  cp * rho * Cw * U_wind

    C = - cp * rho * Cw * U_wind * T_env - Q_dc - S_flux*(1-alpha)

    coeffs = [A,0,0,B,C]

    roots = np.roots(coeffs)
    sols=[]
    for value in roots:
        if ( np.imag(value)==0 ) & (np.real(value)>=0):
            sols.append(np.round((np.real(value)),2))

    print("Equilibrium temperature(s) due to datacenter heating (Celsius): ", sols[0] - 273.15)

def wind_model():
    Q_dc = 1000 #W.m^-2
    L_dc = 100 #m
    L_bd = 100 #m
    U_wind = 1   #m.s^-1
    rho = 1.293 #kg.m^-3
    cp = 1004 #J.(kg.K)^-1
    Cw = 1
    T_env = 23 + 273.15 #K

    T_bl = T_env + (Q_dc * L_dc) / (cp * rho * Cw * U_wind * L_bd)
    print("Boundary layer temperature due to datacenter heating (Celsius): ", np.round(T_bl - 273.15,2))



"""
Tbl=sols[0]
T1 = Tbl/(2**0.25)
Flux__out = emiss * sigma * T1**4 + (1-emiss)*sigma * Tbl**4
print("Outgoing longwave flux at equilibrium (W.m^-2): ", np.round(Flux__out,2))
print("Solar flux absorbed: ", np.round(S_flux*(1-alpha),2))
print("Datacenter heating flux: ", Q_dc)
"""

